Update axolotl and configs (#21)
* Update axolotl and configs

* Set eval sample packing to True

* remove deprecated fields

diff --git a/Dockerfile-notebook b/Dockerfile-notebook
--- a/Dockerfile-notebook
+++ b/Dockerfile-notebook
@@ -1,7 +1,7 @@
-FROM tfy.jfrog.io/tfy-images/jupyter:0.3.8-cu121-py3.11.10-sudo
+FROM tfy.jfrog.io/tfy-images/jupyter:0.4.1-cu124-py3.11.10-sudo
 SHELL ["/bin/bash", "-c"]
 USER root
-RUN [ "$(/usr/local/cuda/bin/nvcc --version | egrep -o "V[0-9]+\.[0-9]+" | cut -c2-)" = "12.1" ] || (echo "Error: CUDA version is not 12.1" && exit 1)
+RUN [ "$(/usr/local/cuda/bin/nvcc --version | egrep -o "V[0-9]+\.[0-9]+" | cut -c2-)" = "12.4" ] || (echo "Error: CUDA version is not 12.4" && exit 1)
 ENV TORCH_CUDA_ARCH_LIST="7.0 7.5 8.0 8.6 8.9 9.0+PTX"
 ENV DEBIAN_FRONTEND=noninteractive
 # upgrade libnccl
